### PR TITLE
add github workflow

### PR DESCRIPTION
**Pull request by jswhisperer**
initial commit

### CODE REVIEW

**Comment by jswhisperer** [comment]
WIP needs some secrets added and testing

**Comment by jswhisperer** [comment]
Based on https://github.com/tauri-apps/tauri-action

**Comment by jswhisperer** [comment]
I think just add two secrets to the repo, a [GITHUB_TOKEN](https://github.com/imrofayel/fylepad/pull/16/files#diff-409fea45635f464aa0592700a92cf483be2f5b21b60f8f1b383756067ee79213R62) with the permissions:
Screenshot 2024-11-30 at 12 34 08 AM

and the tiptap token labelled [NPM_TOKEN](https://github.com/imrofayel/fylepad/pull/16/files#diff-409fea45635f464aa0592700a92cf483be2f5b21b60f8f1b383756067ee79213R58)


https://docs.github.com/en/actions/security-for-github-actions/security-guides/using-secrets-in-github-actions#creating-secrets-for-a-repository

https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token

**Comment by imrofayel** [comment]
@jswhisperer I'm a dumb junior dev. I'm glad my work got contribution but I need time to understand the workflow. If you explain what is to do from my side, it would be helpful.

Thank you so much! Have a good day 🕊️

**Comment by jswhisperer** [comment]
No issue, never feel dumb please! It takes is something I learned later it takes a stronger developer to ask for help/questions!

No one will hire me and I'm bored so no issues about the contributing, I like @tauri so a learning curve for me too.

Let me know if these releases work for you? https://github.com/jswhisperer/fylepad/releases/tag/app-v0.3.0
You have Windows?

**Comment by jswhisperer** [comment]
If so 
- click https://github.com/imrofayel/fylepad/settings/secrets/actions
- and click create new secret
- NPM_TOKEN with you're tiptap token "long string" from here https://cloud.tiptap.dev/pro-extensions ("image below")

image

image

**Comment by jswhisperer** [comment]
I cannot unless I'm an admin on the repo

**Comment by jswhisperer** [comment]
closing in favour of https://github.com/imrofayel/fylepad/pull/17

**Pull request closed without merging**
