### PR TITLE
multi release workflow new

### PR DESCRIPTION
**Pull request by jswhisperer**
multi release workflow new

### CODE REVIEW

**Comment by imrofayel** [comment]
@jswhisperer Thank you again for your time! I really appreciate your efforts.

1. That `Release App v0.3.0` on your fork worked on `Windows 11` on both of my devices.

2. I've added `NPM_TOKEN` secret, I didn't know it was this easy. Do we have to add `GITHUB_TOKEN` as well?

Did you tested on `Mac`? when we can merge this pull request or there is something we still need to do?

Can I ask how you see this app? like what things you missing in this and any other feedback.

Have a great day 🕊️

**Comment by jswhisperer** [comment]
Merge it now as is yes 👍 No need for GITHUB_TOKEN I read and tested.

it will trigger a build right now every time on MAIN branch or if you add a GIT tag in the format v0.0.0 it looks in Cargo.toml for the version but I generally update package.json and tauri.conf.json to be safe.

**Comment by jswhisperer** [comment]
It works on both Mac builds too

**Comment by imrofayel** [comment]
@jswhisperer thankyou for your contribution!

**Pull request merged**
